### ISSUE TITLE
IO-like objects handled gracefully

### ISSUE THREAD

**Issue by jbielick** [monterail/saxy#3]
I noticed in writing a small sample script to try Saxy out that `ARGF` wasn't handled. Threw an error about trying to get the class name of the object. `ARGF` is IO-like, but not actually an ancestor of `IO`. Seems like Nokogiri gracefully duck-types this IO object in either `parse` or `parse_io`. 

Could https://github.com/monterail/saxy/blob/master/lib/saxy/parser.rb#L71 check for an IO-like interface instead of class ancestry?

I'd be more than happy to supply a PR, just let me know if you're interested.

**Comment by szajbus** [comment]
@jbielick definitely something I would put into saxy. Looking forward to PR :)

**Comment by jbielick** [comment]
https://github.com/monterail/saxy/pull/4
